services:
  postgres:
    image: postgres:16
    container_name: ecom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kick
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
