name: 'ecom_dbt'
version: '1.0.0'
profile: 'ecom_dbt'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecom_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
